### ISSUE TITLE
Use Tauri's http module to bypass CORS

### ISSUE THREAD

**Issue by KaKi87** [liudonghua123/hoppscotch-app#1]
https://tauri.studio/en/docs/api/js/modules/http/

Or, you can also use [`axios`](https://www.npmjs.com/package/axios) with [`axios-tauri-adapter`](https://www.npmjs.com/package/axios-tauri-adapter).

Thanks

**Comment by liudonghua123** [comment]
Could you please provide more details about this issue? For example, what's the problem with which situation?

> https://tauri.studio/en/docs/api/js/modules/http

It seems only a new `window.http` API is provided by tauri.

**Comment by KaKi87** [comment]
> Could you please provide more details about this issue? For example, what's the problem with which situation?

[CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) is one of the reasons why hoppscotch features a [proxy](https://github.com/hoppscotch/hoppscotch/blame/main/README.md#L175) and [browser extensions](https://github.com/hoppscotch/hoppscotch/blame/main/README.md#L210).

[CORS also applies to Tauri, and using the `http` module is the recommended way of bypassing it](https://github.com/tauri-apps/tauri-docs/issues/26#issuecomment-836609507).

And, since I use `axios` in my projects, I created an [adapter](https://github.com/axios/axios/blob/master/lib/adapters/README.md) for it that uses Tauri's `http` module, just like `axios` has an [`xhr` adapter](https://github.com/axios/axios/blob/master/lib/adapters/xhr.js) for browsers' [`XMLHttpRequest`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) class and an [`http` adapter](https://github.com/axios/axios/blob/master/lib/adapters/http.js) for Node's [`http`](https://nodejs.org/api/http.html) module.

> It seems only a new `window.http` API is provided by tauri.

Actually, it's `window.__TAURI__.http`, and is only enabled when `tauri.conf.json` contains `tauri.allowlist.http.all = true`.
But, what do you mean by *only a new API is provided* ?

Also, since hoppscotch is bundled, you can import the [`@tauri-apps/api` package](https://www.npmjs.com/package/@tauri-apps/api) using `import { http } from '@tauri-apps/api'`.

**Comment by liudonghua123** [comment]
@KaKi87 Thanks for your detailed explanation. Now I see how to do next.
From the code of [hopscotch](https://github.com/hoppscotch/hoppscotch) and [hoppscotch-extension](https://github.com/hoppscotch/hoppscotch-extension). I understand how the actual network request works.

From https://github.com/hoppscotch/hoppscotch/blob/main/packages/hoppscotch-app/helpers/network.ts, if browser extension is installed and settings is enabled, then the actual network provider is proxied to `window.__POSTWOMAN_EXTENSION_HOOK__.sendRequest` instead of the default `axios`.
```js
const runAppropriateStrategy = (req: AxiosRequestConfig) => {
  if (isExtensionsAllowed() && hasExtensionInstalled()) {
    return ExtensionStrategy(req)
  }

  return AxiosStrategy(req)
}
```
And in the https://github.com/hoppscotch/hoppscotch-extension/blob/master/src/hookContent.js, `window.__POSTWOMAN_EXTENSION_HOOK__` is implemented and injected as a content script. Then the axios (https://github.com/hoppscotch/hoppscotch-extension/blob/07c4c7d556d89dfbf1ed98183c05bbb384cb7840/src/index.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L164-L191) is used in the browser's background script. Because it is run in this context, maybe cors is not affected.
```js
window.__POSTWOMAN_EXTENSION_HOOK__ = {
// ...
  sendRequest: (config) => new Promise((resolve, reject) => {
// ...
}
```

So I need to inject a `window.__POSTWOMAN_EXTENSION_HOOK__.sendRequest` which use the http module in [@tauri-apps/api](https://www.npmjs.com/package/@tauri-apps/api).

**Comment by liudonghua123** [comment]
@KaKi87 I tried to patch `hoppscotch/packages/hoppscotch-app/helpers/strategies/ExtensionStrategy.ts`, see https://github.com/liudonghua123/hoppscotch-app/commit/f40e92b0723d91a77caaf570d3256ec14c7a0a6d for these changes. I tested and it worked for a few simple test.

**Comment by KaKi87** [comment]
Would an `AppImage` download be available to preview this change ? Thanks

**Comment by liudonghua123** [comment]
> Would an `AppImage` download be available to preview this change ? Thanks

`AppImage` for linux is already available in the release page, you can download and try it, I only tested a few   simple usage.

**Comment by KaKi87** [comment]
Are you sure this change is included in the last release ?

Because all requests to CORS-protected enpoints don't work for me.

**Comment by masterjanic** [comment]
@KaKi87 I know this is an old issue, but I need to connect a websocket with a specific Origin header from my frontend. Is there any way to use this http module for websocket connections (wss)?

**Comment by KaKi87** [comment]
I'm not this app's maintainer.

**Comment by liudonghua123** [comment]
@masterjanic @KaKi87 Hi, I updated the app, and fixed some problems with http body parse issues. Maybe you could try the latest release binaries.

**Comment by KaKi87** [comment]
Actually, after installing the latest version, I'm stuck on a spinner.

Thanks

**Comment by liudonghua123** [comment]
@KaKi87 Hi, I tried the latest 23.8.3 version of this app on windows 11, and it worked for me. Could you share more details about your problem like execution environments, snapshots and errors shown in the console of dev-tools (right click the app and select `Inspect`).

**Comment by KaKi87** [comment]
Same version on Ubuntu Unity 23.04 installed using `hoppscotch-app-linux-23.8.3_amd64.deb` :

![](https://github.com/liudonghua123/hoppscotch-app/assets/21284089/512ff84b-9355-4f78-8204-3009f7a8f69a)

**Comment by Walker-00** [comment]
> Same version on Ubuntu Unity 23.04 installed using `hoppscotch-app-linux-23.8.3_amd64.deb` :
> 
> ![](https://private-user-images.githubusercontent.com/21284089/282282807-512ff84b-9355-4f78-8204-3009f7a8f69a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MTY3NjEsIm5iZiI6MTcxNTUxNjQ2MSwicGF0aCI6Ii8yMTI4NDA4OS8yODIyODI4MDctNTEyZmY4NGItOTM1NS00Zjc4LTgyMDQtMzAwOWY3YThmNjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDEyMjEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNDJmZDRhMWQ4MmY2YjM4MDU1MjY5MTZkZWJlZjJlMzcxZjZkZGFkYTg5NWY0OGYzNGNkYmUyZjE0MTJkMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O5959y49w6NSSaa4iQoE6bHIAHbOhBSvVx25I-R5dgA)

same issue with same error

**Comment by KaKi87** [comment]
Hi,
I recently discovered there is now an official multiplatform desktop Hoppscotch app, also made with Tauri, that successfully bypasses CORS.
Downloads : https://hoppscotch.com/download
Source code : https://github.com/hoppscotch/hoppscotch/tree/main/packages/hoppscotch-selfhost-desktop
