### ISSUE TITLE
not work ip address in 127.0.0.1 or localhost

### ISSUE THREAD

**Issue by sweetwisdom** [liudonghua123/hoppscotch-app#12]
![image](https://github.com/user-attachments/assets/b1288554-d568-4c02-948b-2d8751956176)

when i  send request  http://127.0.0.1:9999/ on my local pc,it doesn't work

however it can work  in edge browser

![image](https://github.com/user-attachments/assets/760a715b-3e92-4c84-8f70-13db9c1dbcfa)

**Comment by liudonghua123** [comment]
> ![image](https://github.com/user-attachments/assets/b1288554-d568-4c02-948b-2d8751956176)

In this picture, I noticed that you didn't choose `Browser extension` as interceptor, or you will get [CORS](https://javascript.info/fetch-crossorigin#why-is-cors-needed-a-brief-history) issues.

**Comment by sweetwisdom** [comment]
Thank you, I solved this problem using the official windows version.
use `native` mode  solved this problem

![image](https://github.com/user-attachments/assets/87473aaa-da8b-4e11-8bf4-93e26532dbec)

> https://hoppscotch.com/download

**Comment by liudonghua123** [comment]
Yes, the official desktop version support more features like cert. But the tauri used is still v1 which do not support mobile platform and maybe it will be updated soon.

And this project is a simple tauri package app of [hoppscotch web](https://github.com/hoppscotch/hoppscotch/tree/main/packages/hoppscotch-selfhost-web) and only try to overwrite the underling network provided by tauri as less as possible, see also [postwoman_extension_hook_patch.txt](https://github.com/liudonghua123/hoppscotch-app/blob/main/postwoman_extension_hook_patch.txt).
