### ISSUE TITLE
"hopscotch-app" is damaged

### ISSUE THREAD

**Issue by jyeung79** [liudonghua123/hoppscotch-app#2]
I'm getting this error when I try to open the M1 build version. I'm using a MBP 16 M1 Pro on Monterey 12.1.

```
“hoppscotch-app” is damaged and can’t be opened. You should move it to the Trash.
```

I'm unsure what the reason or issue is with the dmg files.

**Comment by liudonghua123** [comment]
Maybe you need to remove some metadata of the file you download using [xattr](https://eclecticlight.co/2017/12/11/xattr-com-apple-quarantine-the-quarantine-flag/) command like `xattr -d com.apple.quarantine hoppscotch-app-macos-2.2.1_x64.app.zip`.

![image](https://user-images.githubusercontent.com/2276718/193173888-b982761b-46b8-4308-b483-f4f8119ea1a4.png)

![image](https://user-images.githubusercontent.com/2276718/193173976-5d82eab7-a1a3-432d-9119-1c01178124df.png)
