### ISSUE TITLE
Cannot log in with GitHub

### ISSUE THREAD

**Issue by wvffle** [liudonghua123/hoppscotch-app#3]
When I click the button to log in with GitHub, the loader spins but nothing happens.

I guess it should open up a new window (or browser window) to perform an OAuth authentication

**Comment by liudonghua123** [comment]
Um, I haven't tested github authentication, This app is just a lightweight wrapper of static files of hopscotch using tauri, packaged as a desktop offline app, and [a tauri proxy backend](https://github.com/liudonghua123/hoppscotch-app/blob/main/postwoman_extension_hook_patch.txt) is included to bypass [cors](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) problems.

**Comment by mogita** [comment]
Actually no login method works for me at this moment. I got "no reaction" with either GitHub, Google or Microsoft options. I got "Network Error" with Email. I'm unfamiliar with Tauri but it might be some proxy issue?

**Comment by liudonghua123** [comment]
This app is just some static files served locally, no backend service provided. So some feature depend on backend service might not work.
