### ISSUE TITLE
GLIBC 要求过高，建议把glibc 降两个版本打包

### ISSUE THREAD

**Issue by lnxyz** [liudonghua123/hoppscotch-app#5]
os: debian 11 run hoppscotch-app 3.0.1 appimage error .

当前软件打包要求为 glibc2.33+   目前 主流的 如 debian 11 还在 glibc2.31  (uos deepin base on debian 11)
建议把 glibc 降一下。

**Comment by liudonghua123** [comment]
Ok, I will try to build with ubuntu 20.04 instead of 22.04 later.
