### ISSUE TITLE
“hoppscotch-app” is damaged and can’t be opened. 

### ISSUE THREAD

**Issue by fbradyirl** [liudonghua123/hoppscotch-app#8]
Build 23.8.1 on Apple Silicon is not opening for me with this error:

![image](https://github.com/liudonghua123/hoppscotch-app/assets/254309/3a0f59e8-42db-4f4f-81d7-f6c216fb8971)

**Comment by mercxry** [comment]
I'm getting the same thing on a M1 Pro

**Comment by fbradyirl** [comment]
Workaround worked for me. Follow 

https://github.com/liudonghua123/hoppscotch-app/issues/2

**Comment by liudonghua123** [comment]
After you download the app whether in executable, zip or dmg format on macos, use `xattr -d com.apple.quarantine <hoppscotch-app>` before running or installing. This should work.
